### ISSUE TITLE
self.network not defined, should be changed to self.model

### ISSUE THREAD

**Issue by chinmay0301** [princetonvisualai/gan-debiasing#1]
https://github.com/princetonvisualai/gan-debiasing/blob/505f085ed90f7e4c2585c0a49d47ea7aea3c70b2/Models/attr_classifier.py#L43

**Comment by chinmay0301** [comment]
`self.network.train()` should be changed to `self.model.train()`

**Comment by vramaswamy94** [comment]
Thanks, this has been fixed.
