### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/fake_images/Smiling_scores.pkl'

### ISSUE THREAD

**Issue by randomstudentid** [princetonvisualai/gan-debiasing#12]
Hello,

I was trying to run your code and I have been struggling with an error for the past few hours.

This is the error that I met when I tried to run python main.py --experiment model: 
FileNotFoundError: [Errno 2] No such file or directory: 'data/fake_images/Smiling_scores.pkl'

I have followed your steps on the readme and I haven't found out where in the code this file is being created.

Full output:
{'experiment': 'model', 'experiment_name': '_', 'real_data_dir': 'data/celeba', 'fake_data_dir_orig': 'data/fake_images/AllGenImages/', 'fake_data_dir_new': '_', 'fake_scores_target': '_', 'fake_scores_protected': '_', 'cuda': True, 'random_seed': 0, 'attribute': 31, 'protected_attribute': 20, 'test_mode': False, 'num_train': 160000, 'number': 0, 'device': device(type='cuda'), 'dtype': torch.float32, 'print_freq': 100, 'total_epochs': 20, 'save_folder': 'record/model\\Smiling', 'optimizer_setting': {'optimizer': <class 'torch.optim.adam.Adam'>, 'lr': 0.0001, 'weight_decay': 0}, 'dropout': 0.5, 'data_setting': {'real_params': {'path': 'data/celeba', 'attribute': 31, 'protected_attribute': 20, 'number': 0}, 'fake_params': {'path_new': 'data/fake_images/Smiling/', 'path_orig': 'data/fake_images/AllGenImages/', 'attr_path': 'data/fake_images/Smiling_scores.pkl', 'dom_path': 'data/fake_images/all_Male_scores.pkl', 'range_orig_image': (15000, 175000), 'range_orig_label': (160000, 320000), 'range_new': (0, 160000)}, 'augment': True, 'params_train': {'batch_size': 32, 'shuffle': True, 'num_workers': 0}, 'params_val': {'batch_size': 64, 'shuffle': False, 'num_workers': 0}}}
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main(opt)
  File "main.py", line 63, in main
    train = create_dataset_all(
  File "load_data.py", line 60, in create_dataset_all
    labeldata = pickle.load(open(fake_params['attr_path'], 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/fake_images/Smiling_scores.pkl'

**Comment by vramaswamy94** [comment]
The issue is that you haven't hallucinated scores for the generated images. Try running `get_scores.py` to do so, and change the path to the location where the scores are stored.

**Comment by randomstudentid** [comment]
Hello,

Thank you for your quick response.

Could you help me with the syntax of this command?

Let's say I wanted to hallucinate the labels for Male what is the correct
way to invoke get_scores.py?

Thank you again for your help and time.

**Comment by vramaswamy94** [comment]
See command line arguments here: https://github.com/princetonvisualai/gan-debiasing/blob/5f9898b01779b0dc10bbfbc7008fec4f6f88e572/parse_args.py#L1:~:text=def%20collect_args_scores()%3A

**Comment by randomstudentid** [comment]
would this be the correct invocation?

```python get_scores.py --attribute 31 --out_file data/fake_images/Smiling_scores.pkl```

**Comment by junjie1003** [comment]
> would this be the correct invocation?
> 
> `python get_scores.py --attribute 31 --out_file data/fake_images/Smiling_scores.pkl`

Hello, have you resolved this issue? Should I need to generate scores for the newly generated images "data/fake_images/Straight_Hair/*"? If I only modify the `out_file` parameter, it seems like `get_scores.py` is still hallucinating scores for the original images "data/fake_images/AllGenImages/*" instead of the newly generated ones.
