### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/fake_images/Straight_Hair_scores.pkl'

### ISSUE THREAD

**Issue by junjie1003** [princetonvisualai/gan-debiasing#13]
Hello, I was trying to run your code and I have been struggling with an error for the past few hours. This is the error that I met when I tried to run python main.py --experiment model. I saw your previous response, but I have a confusion. You said that running get_scores.py and change the path to the location where the scores are stored could solve it. Should I need to generate scores for the newly generated images "data/fake_images/Straight_Hair/"? If I only modify the out_file parameter, it seems like get_scores.py is still hallucinating scores for the original images "data/fake_images/AllGenImages/" instead of the newly generated ones. What command should I need to run to generate the final Straight_Hair_scores.pkl file that I want? It seems like `python get_scores.py --attribute 32 --out_file data/fake_images/Straight_Hair_scores.pkl` doesn't achieve the desired outcome I'm aiming for.

**Comment by vramaswamy94** [comment]
Hi, 
I'm unsure what data/fake_images/Straight_Hair contains. Does it contain the randomly sampled fake images? Or the perturbed ones? The perturbed images do not need scores, the assumption is that they have the same label as the randomly generated images.

**Comment by junjie1003** [comment]
data/fake_images/Straight_Hair contains perturbed images which are generated by `python generate_images.py --experiment pair --attribute 32` command. So I only need to run `python get_scores.py --attribute 32 --out_file data/fake_images/Straight_Hair_scores.pkl`? And data/fake_images/all_Straight_Hair_scores.pkl and data/fake_images/Straight_Hair_scores.pkl are actually the same scores, right? Thank you very much!

**Comment by vramaswamy94** [comment]
Yes, that's correct.
