### ISSUE TITLE
Crash main.py#144

### ISSUE THREAD

**Issue by dominikzietlow** [princetonvisualai/gan-debiasing#3]
deo, deo_std = utils.bootstrap_deo(val_targets[:, 1], val_targets[:, 0], val_pred)

bootstrap_deo doesnt have a default value for repeats

**Comment by dominikzietlow** [comment]
also in utils.py:

#179 and following:
def smoothed_hist_kl_distance(a, b, nbins=50, sigma=1):
    ahist = np.histogram(a, bins=nbins)[0]
    bhist = np.histogram(b, bins=nbins)[0]

    asmooth = gaussian_filter(ahist, sigma)
    bsmooth = gaussian_filter(bhist, sigma)

    asmooth = asmooth/asmooth.sum() + 1e-6
    bsmooth = bsmooth/bsmooth.sum() + 1e-6

    return kl(asmooth, bsmooth), kl(bsmooth, asmooth)
    
    
guassian_filter is not defined


#318+
targets_all not defined
scores_all not defined
domain_all not defined


#351+
all the lists are not initialized


maybe that code is dead?

**Comment by vramaswamy94** [comment]
I think this has been fixed now, thanks for pointing it out!
