### ISSUE TITLE
f1_score and f1_thresh swapped?

### ISSUE THREAD

**Issue by falloncandra** [princetonvisualai/gan-debiasing#4]
in main.py line 139
f1_score, f1_thresh = utils.get_threshold(val_targets[:, 0], val_scores)
https://github.com/princetonvisualai/gan-debiasing/blob/cdaa0f3b1ea65d6eaefb0955c4da1b7ed5c44b5e/main.py#L139

However, in utils.py line 164
return best_t, best_acc
https://github.com/princetonvisualai/gan-debiasing/blob/cdaa0f3b1ea65d6eaefb0955c4da1b7ed5c44b5e/utils.py#L164

it returns threshold first, instead of score.

Is this a mistake?
because f1_thresh is needed to hallucinate labels in get_scores.py

**Comment by vramaswamy94** [comment]
Yup, thanks for pointing it out!
