### ISSUE TITLE
function create_dataset_all in load_data.py 

### ISSUE THREAD

**Issue by ltl7155** [princetonvisualai/gan-debiasing#7]
In my opinion, this function is for building a dataset to integrate both fake images and original training data.  
The code part that I have questions about is
`labeldata = pickle.load(open(fake_params['attr_path'], 'rb'))
 labeldata = np.tile(labeldata, 2)`

The range of labeldata is (0, 175000) before np.tile. However, when assigning the label to fake images, you assign the samples in (15000, 175000) as lables in (0, 160000). Is it a misalignment? 
Or there must be some unknown extra preprocessing in "all_{}_scores.pkl".

Should I process it as the domdata?

**Comment by vramaswamy94** [comment]
The first 15000 fake images are used to learn the separating hyperplane, we do not generate the flipped image for those.

**Comment by ltl7155** [comment]
Thanks for your response. I totally understand all you explained. The labeldata you load in `labeldata = pickle.load(open(fake_params['attr_path'], 'rb')) labeldata = np.tile(labeldata, 2)` contains 175000 items. The domdata also contains 175000 items and you remove the first 15000 fake images, which is reasonable. However, you don't remove the first 15000 fake images for labeldata in your code. My question is , should I also remove the first 15000 fake images of labeldata just like domdata to avoid the misalignment problem?

Expecting your response.

**Comment by vramaswamy94** [comment]
Right, we preprocessed the target attribute labels to start at 15000. Sorry about the confusion!
