### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/fake_images/all_Male_scores.pkl'

### ISSUE THREAD

**Issue by dileeppanigrahi** [princetonvisualai/gan-debiasing#8]
Hi All, 
I've recently started working on checking the Fairness of the model on visualization tasks.  

while running the linear.py code (`gan-debiasing project`) I got the exception telling FileNotFoundError: all_Male_scores.pkl.  

please let me know if I'm doing any mistakes running in the below procedure :

1. Downloaded `CelebA` dataset and put it in data/celeb
2. Ran `crop_images.py` to crop the images 128*128
3. Ran main.py --experiment baseline to train a standard attribute classifier for each target attribute
4. Ran `generate_images.py --experiment orig`
5. Ran `get_scores.py` -->Note: it was only generating the all_Smiling_scores.pkl file . it was not generating the 'all_Male_scores.pkl' file.
6. Ran `linear.py` --> throws an  exception( "all_Male_scores.pkl file not found error")

Thanks.

**Comment by vramaswamy94** [comment]
Hi, 

`get_scores.py` takes in a command line argument with the attribute. You need to (1) run `main.py` for both the protected and target attributes, and (2) run `get_scores.py` with both the protected and target attributes.

**Comment by dileeppanigrahi** [comment]
> Hi,
> 
> `get_scores.py` takes in a command line argument with the attribute. You need to (1) run `main.py` for both the protected and target attributes, and (2) run `get_scores.py` with both the protected and target attributes.

Hi @vramaswamy94 , thank you for your suggestion . Sorry, can you please provide the steps how to run `main.py` and `get_scores.py ` for both target and protected attributes (command-line arguments)

**Comment by dileeppanigrahi** [comment]
@vramaswamy94 ,can you please suggest, how to run `main.py` on the protected attribute.
