### ISSUE TITLE
How to run `main.py` file for both target and protected attribute

### ISSUE THREAD

**Issue by dileeppanigrahi** [princetonvisualai/gan-debiasing#9]
Hi, 

`get_scores.py` takes in a command line argument with the attribute. You need to (1) run `main.py` for both the protected and target attributes, and (2) run `get_scores.py` with both the protected and target attributes.

_Originally posted by @vramaswamy94 in https://github.com/princetonvisualai/gan-debiasing/issues/8#issuecomment-940905810_

can you please provide the steps on how to run `main.py` for both target and protected attributes (commands to run the main.py file ).

Thank you in advance.

**Comment by vramaswamy94** [comment]
`python main.py --experiment baseline --attribute <attribute number>`

**Comment by dileeppanigrahi** [comment]
Thank you @vramaswamy94 , so I need to run `main.py` for 2 times , one for the target attribute another is the protected attribute
python main.py --experiment baseline --attribute 31   # target
python main.py --experiment baseline --attribute 20   # protected attribute

**Comment by vramaswamy94** [comment]
Yes

**Comment by dileeppanigrahi** [comment]
> Yes

Thank you so much for the confirmation
